### ISSUE TITLE
Do not open Booth page on startup / 起動時にブースページを開かないでください

### ISSUE THREAD

**Issue by seascape** [YukiYukiVirtual/OpenBrowserServer#7]
When the user starts OpenBrowserServer, it opens the web page https://yukiyukivirtual.booth.pm/items/2539784 in user's default web browser.

Please add an option to do nothing at startup (do not open a web page).

One reason is that the user may not want their web browser to open when they start their PC.

Thank you for the app!

---

Machine translation / 機械翻訳:

ユーザーがOpenBrowserServerを起動すると、ユーザーのデフォルトのWebブラウザーでWebページ https://yukiyukivirtual.booth.pm/items/2539784 が開きます。 

起動時に何もしないオプションを追加してください（Webページを開かないでください）。

1つの理由は、ユーザーがPCの起動時にWebブラウザーを開かないようにする場合があるためです。

アプリありがとうございます！

**Comment by YukiYukiVirtual** [comment]
拙作を使ってくださりありがとうございます。
リンク先で購入していただくことで、起動時にページが開かないものをダウンロード出来ます。
https://yukiyukivirtual.booth.pm/items/2539784

please translate yourself
